-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 00:13:15 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`System`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`System` ;

CREATE TABLE IF NOT EXISTS `mydb`.`System` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `power` INT NULL,
  `mission` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Mashine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Mashine` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Mashine` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `power` INT NULL,
  `System_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `System_ID`),
  INDEX `fk_Mashine_System_idx` (`System_ID` ASC),
  CONSTRAINT `fk_Mashine_System`
    FOREIGN KEY (`System_ID`)
    REFERENCES `mydb`.`System` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Component`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Component` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Component` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `manufacturer` VARCHAR(45) NULL,
  `power` INT NULL,
  `Mashine_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Mashine_ID`),
  INDEX `fk_Component_Mashine1_idx` (`Mashine_ID` ASC),
  CONSTRAINT `fk_Component_Mashine1`
    FOREIGN KEY (`Mashine_ID`)
    REFERENCES `mydb`.`Mashine` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`System`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`System` (`ID`, `name`, `power`, `mission`) VALUES (DEFAULT, 'System1', 25, 'Server');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Mashine`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Mashine` (`ID`, `name`, `power`, `System_ID`) VALUES (DEFAULT, 'Machine1', 10, DEFAULT);
INSERT INTO `mydb`.`Mashine` (`ID`, `name`, `power`, `System_ID`) VALUES (DEFAULT, 'Machine2', 10, DEFAULT);
INSERT INTO `mydb`.`Mashine` (`ID`, `name`, `power`, `System_ID`) VALUES (DEFAULT, 'Machine3', NULL, DEFAULT);

COMMIT;

